[package]
name = "trello-set-list"
version = "0.1.0"
authors = ["Brandon Huber <brandon.e.huber@gmail.com>"]

[dependencies]
pulldown-cmark = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
clap = "2.31"
textwrap = "0.10.0"
time = "0.1"
